---
title: "Past R Events Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    self_contained: false
    includes:
      after_body: "afterInit.html"
      #beforeInit: "afterInit.html"
      
    css: css/custom.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(countrycode)
library(lubridate)
options(DT.options = list(scrollY="250px",scrollX="50px", pageLength = 10, autoWidth = TRUE))
library(echarts4r)
source("past_events.R")
```

Sidebar {.sidebar data-width=200}
=====================================

<div class="sidebar-pages">
<a class="navlink" href="#home" data-toggle="tab" aria-expanded="false"><i class="fa fa-home"></i> Past R Events</a>
</div>


Past R Events
=====================================

Row
-------------------------------------

### Total Events

```{r}

valueBox(total_events, icon = "fa-calendar", color = "#1F51FF")

```

### Total Attendees

```{r}

valueBox(total_rsvp, icon = "fa-users", color = "#1F51FF")

```

### Events - Cities

```{r}
valueBox(total_cities, icon = "fa-building", color = "#1F51FF")
```

### Events - Countries

```{r}
valueBox(total_countries, icon = "fa-globe", color = "#1F51FF")
```

Row {data-height=500}
-----------------------------------------------------------------------

### Number of R Events held across Regions of Globe

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")

region_df %>% 
  arrange(desc(Events_freq)) %>%
  e_charts(group_region) %>%
  e_bar(serie = Events_freq) %>% 
  e_title(text = "R Events Across Regions", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Attendance in R Events across Regions

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")

region_df_rsvp %>% 
  arrange(desc(attendees)) %>%
  e_charts(group_region) %>%
  e_bar(serie = attendees) %>% 
  e_title(text = "R Event Attendance", 
          subtext = "RSVP Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=800}
-----------------------------------------------------------------------

### Top 40 City destinations for R events

```{r}
top_dest_city <- top_dest_city %>%
  arrange(Events_freq)

mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")
top_dest_city %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title("Top Cities for R Events", "City") %>% 
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>% 
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

### Timeline for Cumulative Growth of R events

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")
cumm_event_count %>%
  e_charts(local_date) %>%
  e_area(csum, name = "Cumulative Event Count", legend = FALSE) %>%
  e_datazoom(type = "slider") %>%
  e_zoom(dataZoomIndex = 0,
         start = 0,
         end = 100) %>% 
  e_title(text = "Growth of R Events across years", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=1000}
-----------------------------------------------------------------------

### Top Destinations for R events | <small> Event count per city per region </small>

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")
plot1 <- tail(df1, 10) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Africa Region", 
          subtext = "Top 10 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot2 <- tail(df2, 20) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Latin America Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot3 <- tail(df3, 20) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Asia Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot4 <- tail(df4, 10) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Australia Region", 
          subtext = "Top 10 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot5 <- tail(df5, 20) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "US/Canada Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

plot6 <- tail(df6, 20) %>%
  e_charts(x = venue_city) %>%
  e_bar(Events_freq, legend = FALSE, name = "Events Count") %>% 
  e_labels(position = "right") %>% 
  e_title(text = "Europe Region", 
          subtext = "Top 20 Cities", 
          sublink = "#",
          left = "left", top = 4) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"))) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_flip_coords() %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)

e_arrange(plot5, plot6, plot3, plot2, plot1, plot4, rows = 3, cols = 3)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Top Destinations for R Events | <small> Users per Country

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")

top_dest_country %>% 
  arrange(desc(attendees)) %>%
  e_charts(venue_country_name) %>%
  e_bar(serie = attendees) %>% 
  e_title(text = "Top R Event Destinations", 
          subtext = "Attendees Count", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=400}
-----------------------------------------------------------------------

### Top R Events Destinations | <small> Events per Country </small> 

```{r}
mycolor <- c("#1F51FF","#003636","#a9a9a9", "#91c8c8")

events_by_country %>% 
  arrange(desc(Events_freq)) %>%
  e_charts(venue_country_name) %>%
  e_bar(serie = Events_freq) %>% 
  e_title(text = "Top R Events Organizing Countries", 
          subtext = "Frequency of Events", 
          sublink = "#",
          left = "left", top = 4
  ) %>%
  e_y_axis(
    splitArea = list(show = TRUE),
    axisPointer = list(      show = FALSE, 
                             lineStyle = list(
                               color = "#999999",
                               width = 0.75,
                               type = "dotted"
                             ))
  ) %>%
  e_x_axis(splitArea = list(show = TRUE),
           splitLine = list(show = TRUE),
           axisLabel= list(rotate = 30,interval = 0)) %>%
  e_toolbox_feature(feature = "magicType",
                    type = list("area", "line", "bar")) %>%
  e_toolbox_feature("restore") %>%
  e_toolbox_feature(feature = "reset") %>%
  e_toolbox_feature("dataView") %>%
  e_toolbox_feature("saveAsImage") %>%
  e_animation(duration = 1000) %>%
  e_tooltip(trigger = "axis") %>% e_color(mycolor)
```

Row {data-height=500}
-----------------------------------------------------------------------

### Data Table

```{r}
datatable(display_df, filter = "top",
          extensions = c(
            "Buttons",
            "Scroller"),
          rownames = FALSE,
          style = "bootstrap",
          class = "compact",
          width = "auto",
          options = list(
            dom = "Blrtip",
            deferRender = TRUE,
            buttons = list(
              "csv",
              "excel"))
          )
```
